#trigger for the code
name: learn-github-actions
on: [push]
  jobs: 
    check-nodemon-version:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          - with:
              node-version: '14'
        - run: npm install -g nodemon
        - run: nodemon -v